name: PerkSystem
version: '${project.version}'
main: badziol.perksystem.PerkSystem
api-version: 1.19
commands:
  pg:
    description: Komenda do graficznej obslugi perkow
    usage: </command>
  perk:
    description: Komenda dla administratora
    usage: </command>
  ikar:
    description: Uruchomienie Ikara komenda
    usage: </command>
  lowca:
    description: Komenda pomocnicza dla perka Lowca, obslugiwane parametry daj, gracz smierc
    usage: </command>
  ser64:
    description: (testy)Komenda do serializowania przedmiotu w lewej rece metoda base64
    usage: </command>
  serjson:
    description:  (testy)Komenda do serializowania przedmiotu w lewej rece json
    usage: </command>



